#########################
####Edit This Section####
#########################

database: reference_database 
maxlength: chopper_maxrl
minlength: chopper_minrl
minqual: chopper_qual
R1_extension: extension_R1_user
directory_name: dir_name 
create_db: dont #create or dont
ref_cov_cutoff: 50
pident_cutoff: 95
mismatch_cutoff: 11
con_len_cutoff: 1600
scaffold: dont #scaffold or dont

#########################
#########################

#Set kits
barcode_kit: SQK-PBK004

#Get the sample sheet
samples:  samples.tsv



#Reference Databases
phytophthora: /home/shared_docs/databases/phytophthora_metabarcode/phytophthora_ITS_COI_DB_v7.fasta
phytoplasma: /home/shared_docs/databases/phytoplasma_metabarcode/Phpl_DB_99.5.fasta


snakefile_dir:  "/home/PPCDL-bioinf/files/pipelines/minion_metabarcode"

email:
  email: user_email
